import { existsSync, writeFileSync } from "fs";
import { join } from "path";
import chalk from "chalk";
import { loadConfig, DEFAULT_CONFIG } from "../lib/config.js";
import type { Provider } from "../lib/config.js";
import { ContextStore } from "../lib/context-store.js";

export const STARTER_INDEX = `# Project Context

> Auto-generated by [repomemory](https://github.com/DanielGuru/repomemory). Run \`repomemory analyze\` to populate.

## Quick Orient
*Run \`repomemory analyze\` to generate project-specific orientation.*

## Context Files
- \`facts/\` \u2014 Architecture, patterns, integrations
- \`decisions/\` \u2014 Why things are this way (prevents re-debating)
- \`regressions/\` \u2014 Known gotchas, things that broke before
- \`sessions/\` \u2014 Compressed session summaries
- \`changelog/\` \u2014 Recent changes by month
- \`preferences/\` \u2014 Coding style, preferred patterns, tool configs

## For AI Agents
Search this directory for task-relevant context before starting work.
Write new learnings using the \`context_write\` MCP tool during your session.
`;

export function writeDefaultConfigFile(
  repoRoot: string,
  provider: string,
  model: string,
  embeddingProvider?: string
): void {
  const configPath = join(repoRoot, ".repomemory.json");
  if (!existsSync(configPath)) {
    const configToWrite: Record<string, unknown> = {
      provider,
      model,
      contextDir: DEFAULT_CONFIG.contextDir,
      maxFilesForAnalysis: DEFAULT_CONFIG.maxFilesForAnalysis,
      maxGitCommits: DEFAULT_CONFIG.maxGitCommits,
      autoIndex: DEFAULT_CONFIG.autoIndex,
      ignorePatterns: [] as string[],
      keyFilePatterns: [] as string[],
    };
    if (embeddingProvider) {
      configToWrite.embeddingProvider = embeddingProvider;
    }
    writeFileSync(configPath, JSON.stringify(configToWrite, null, 2) + "\n");
  }
}

export const CLAUDE_MD_BLOCK = `## Repository Memory (repomemory)

This repo uses [repomemory](https://github.com/DanielGuru/repomemory) for persistent AI memory.

**IMPORTANT: Before starting ANY task, you MUST call \`context_search\` with relevant
keywords. This is NOT optional. The knowledge base contains architecture docs,
past decisions, and known regressions that WILL save you from mistakes.
Do NOT skip this step even if the task seems simple.**

**ALWAYS at the start of every task:**
1. Call \`context_search\` with keywords related to your task
2. If this is a new session, call \`context_auto_orient\` for a full project overview
3. NEVER propose changes without first checking for past decisions

**During your session:**
- ALWAYS use \`context_write\` to record discoveries, decisions, and gotchas
- ALWAYS use \`context_delete\` to remove stale or incorrect knowledge
- Record coding preferences in \`context_write(category="preferences", ...)\`

**Before modifying code:**
- You MUST search for known regressions related to the component
- You MUST check for past decisions before proposing alternatives
- Call \`context_risk\` with the file paths you plan to modify — it reveals hidden coupling (files that must change together), ownership concentration, and churn hotspots

**At end of session (REQUIRED):**
- Write a session summary: \`context_write(category="sessions", ...)\`
- Route discoveries to the right category (facts/, decisions/, preferences/)`;

export async function initCommand(options: { dir?: string; provider?: string; embeddingProvider?: string }) {
  const repoRoot = options.dir || process.cwd();
  const config = loadConfig(repoRoot);

  if (options.provider) {
    config.provider = options.provider as Provider;
  }

  const store = new ContextStore(repoRoot, config);

  if (store.exists()) {
    console.log(chalk.yellow("\u26a0  .context/ directory already exists."));
    console.log(chalk.dim("  Run `repomemory analyze` to regenerate content."));
    return;
  }

  // Scaffold directories
  store.scaffold();

  // Write starter index
  store.writeIndex(STARTER_INDEX);

  // Write config file
  writeDefaultConfigFile(repoRoot, config.provider, config.model, options.embeddingProvider);

  console.log(chalk.green("\u2713 Initialized .context/ directory\n"));

  console.log(chalk.bold("Next steps:\n"));

  const keyExamples: Record<string, string> = {
    anthropic: "export ANTHROPIC_API_KEY=sk-ant-...",
    openai: "export OPENAI_API_KEY=sk-...",
    gemini: "export GEMINI_API_KEY=...",
    grok: "export GROK_API_KEY=...",
  };
  console.log(`  ${chalk.cyan("1.")} Set your API key:`);
  console.log(chalk.dim(`     ${keyExamples[config.provider] || keyExamples.anthropic}`));
  console.log();

  console.log(`  ${chalk.cyan("2.")} Analyze your repo:`);
  console.log(chalk.dim(`     npx repomemory analyze`));
  console.log();

  console.log(`  ${chalk.cyan("3.")} Connect Claude Code (one-time):`);
  console.log(chalk.dim(`     npx repomemory setup claude`));
  console.log();

  console.log(`  ${chalk.cyan("4.")} Add this to your ${chalk.bold("CLAUDE.md")} so Claude uses it automatically:`);
  console.log();
  console.log(
    chalk.cyan(
      "  \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 copy below into CLAUDE.md \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500"
    )
  );
  console.log();
  console.log(CLAUDE_MD_BLOCK);
  console.log();
  console.log(
    chalk.cyan(
      "  \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500"
    )
  );
  console.log();

  console.log(`  ${chalk.cyan("5.")} Commit to git:`);
  console.log(chalk.dim(`     git add .context/ .repomemory.json CLAUDE.md && git commit -m "Add repomemory"`));
}
